development:
  adapter: postgresql
  encoding: unicode
  database: wildrosedones_development
  pool: 5
  username: kellywaters 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: wildrosedones_test
  pool: 5
  username: kellywaters
  password: 